architecture: MaskRCNN
use_gpu: true
max_iters: 180000
log_smooth_window: 20
save_dir: output
snapshot_iter: 100 #10000
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
metric: COCO
weights: output/mask_rcnn_r50_1x/100
num_classes: 81

# Model Achitecture
MaskRCNN:
  # model anchor info flow
  anchor: Anchor
  proposal: Proposal
  mask: Mask
  # model feat info flow
  backbone: ResNet
  rpn_head: RPNHead
  bbox_head: BBoxHead
  mask_head: MaskHead

ResNet:
  norm_type: bn
  depth: 50
  feature_maps: 4
  freeze_at: 2

RPNHead:
  rpn_feat:
    feat_in: 1024
    feat_out: 1024
  anchor_per_position: 15
  # TODO: move into Anchor part
  # update anchor_generator op to add param for featmap size instead of inputs rpn feat var
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0

BBoxHead:
  bbox_feat:
    feat_in: 1024
    feat_out: 512
    roi_extractor:
      resolution: 14
      sampling_ratio: 0
      spatial_scale: 0.0625
      extractor_type: 'RoIPool'

MaskHead:
  feat_in: 256
  resolution: 14
  mask_feat:
    feat_in: 2048
    feat_out: 256


Anchor:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  #anchor_target_generator:
  #  rpn_batch_size_per_im: 256
  #  rpn_fg_fraction: 0.5
  #  rpn_negative_overlap: 0.3
  #  rpn_positive_overlap: 0.7
  #  rpn_straddle_thresh: 0.0

Proposal:
  proposal_generator:
    min_size: 0.0
    nms_thresh: 0.7
    train_pre_nms_top_n: 12000
    train_post_nms_top_n: 2000
    infer_pre_nms_top_n: 12000
    infer_post_nms_top_n: 2000
    return_rois_num: True
  proposal_target_generator:
    batch_size_per_im: 512
    bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
    bg_thresh_hi: 0.5
    bg_thresh_lo: 0.0
    fg_fraction: 0.25
    fg_thresh: 0.5
  bbox_post_processor: # used in infer
    nms:
      keep_top_k: 100
      score_threshold: 0.05
      nms_threshold: 0.5
      nms_type: 'nms_with_decode'

Mask:
  mask_target_generator:
    resolution: 14

# Infer

# Train
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [120000, 160000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

_READER_: 'mask_reader.yml'
