architecture: MaskRCNN
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
weights: output/mask_rcnn_r50_fpn_1x/model_final
load_static_weights: True

# Model Achitecture
MaskRCNN:
  # model anchor info flow
  anchor: Anchor
  proposal: Proposal
  mask: Mask
  # model feat info flow
  backbone: ResNet
  neck: FPN
  rpn_head: RPNHead
  bbox_head: BBoxHead
  mask_head: MaskHead
  # post process
  bbox_post_process: BBoxPostProcess
  mask_post_process: MaskPostProcess

ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4

FPN:
  in_channels: [256, 512, 1024, 2048]
  out_channel: 256
  min_level: 0
  max_level: 4
  spatial_scale: [0.25, 0.125, 0.0625, 0.03125]

RPNHead:
  anchor_per_position: 3
  rpn_channel: 256

Anchor:
  anchor_generator:
    name: AnchorGeneratorRPN
    aspect_ratios: [0.5, 1.0, 2.0]
    anchor_sizes: [[32], [64], [128], [256], [512]]
    strides: [4, 8, 16, 32, 64]
  anchor_target_generator:
    name: AnchorTargetGeneratorRPN
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.7
    use_random: True #False

Proposal:
  proposal_generator:
    name: ProposalGenerator
    min_size: 0.0
    nms_thresh: 0.7
    train_pre_nms_top_n: 2000
    train_post_nms_top_n: 1000
    infer_pre_nms_top_n: 1000
    infer_post_nms_top_n: 1000
    topk_after_collect: True
  nms_threshold: 0.7
  train_pre_nms_top_n: 2000
  train_post_nms_top_n: 1000
  infer_pre_nms_top_n: 1000
  infer_post_nms_top_n: 1000
  proposal_target_generator:
    name: ProposalTargetGenerator
    batch_size_per_im: 512
    bg_thresh_hi: [0.5,]
    fg_thresh: [0.5,]
    fg_fraction: 0.25
    use_random: True #False

BBoxHead:
  bbox_feat:
    name: BBoxFeat
    roi_extractor:
      name: RoIAlign
      resolution: 7
      sampling_ratio: 0
      aligned: True
    head_feat:
      name: TwoFCHead
      in_dim: 256
      mlp_dim: 1024
  in_feat: 1024

BBoxPostProcess:
  decode:
    name: RCNNBox
    num_classes: 81
    batch_size: 1
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.5

Mask:
  mask_target_generator:
    name: MaskTargetGenerator
    mask_resolution: 28

MaskHead:
  mask_feat:
    name: MaskFeat
    num_convs: 4
    feat_in: 256
    feat_out: 256
    mask_roi_extractor:
      name: RoIAlign
      resolution: 14
      sampling_ratio: 0
      aligned: True
    share_bbox_feat: False
  feat_in: 256


MaskPostProcess:
  mask_resolution: 28
