worker_num: 2
TrainReader:
  inputs_def:
    fields: ['image', 'im_shape', 'scale_factor', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd']
  sample_transforms:
  - DecodeOp: {}
  - RandomFlipOp: {prob: 0.5}
  - NormalizeImageOp: {mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - ResizeOp: {interp: 1, target_size: [800, 1333]}
  - PermuteOp: {}
  batch_transforms:
  - PadBatchOp: {pad_to_stride: -1., pad_gt: true}
  batch_size: 1
  shuffle: true
  drop_last: true


EvalReader:
  inputs_def:
    fields: ['image', 'im_shape', 'scale_factor', 'im_id']
  sample_transforms:
  - DecodeOp: { }
  - NormalizeImageOp: { is_scale: true, mean: [ 0.485,0.456,0.406 ], std: [ 0.229, 0.224,0.225 ] }
  - ResizeOp: { interp: 1, target_size: [ 800, 1333 ] }
  - PermuteOp: { }
  batch_transforms:
  - PadBatchOp: { pad_to_stride: -1, pad_gt: false }
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false


TestReader:
  inputs_def:
    fields: ['image', 'im_shape', 'scale_factor', 'im_id']
  sample_transforms:
  - DecodeOp: { }
  - NormalizeImageOp: { is_scale: true, mean: [ 0.485,0.456,0.406 ], std: [ 0.229, 0.224,0.225 ] }
  - ResizeOp: { interp: 1, target_size: [ 800, 1333 ] }
  - PermuteOp: { }
  batch_transforms:
  - PadBatchOp: { pad_to_stride: -1, pad_gt: false }
  batch_size: 1
  shuffle: false
  drop_last: false
